[nfs]
172.31.18.23 ansible_ssh_user='ec2-user'

[webservers]
172.31.23.42 ansible_ssh_user='ec2-user'
172.31.20.231 ansible_ssh_user='ec2-user'

[db]
172.31.16.235 ansible_ssh_user='ubuntu'

[lb]
172.31.81.146 ansible_ssh_user='ubuntu'