 pipeline {
    agent any


      stage("Initial cleanup") {
          steps {
            dir("${WORKSPACE}") {
              deleteDir()
            }
          }
        }

    stage('Build') {
      steps {
        script {
          sh 'echo "Building Stage"'
        }
      }
    }

    stage('Test') {
      steps {
        script {
          sh 'echo "Testing Stage"'
        }
      }
    }

    stage('Package'){
      steps {
        script {
            sh 'echo "packaging app"'
        }
      }
    } 

    stage('Deploy'){
        steps {
            script {
                sh 'echo "deploying to dev"'
            }
        }    
    }

    stage("clean up"){
        steps {
        cleanWs()
        }
   }

 } 